# Server Port
server.port=8080

# H2 Database Setup
spring.datasource.url=jdbc:h2:mem:bustracking
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console (browser-ൽ ഡാറ്റ കാണാൻ)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Thymeleaf Cache Disable (ഡിസൈൻ പെട്ടെന്ന് മാറി കാണാൻ)
spring.thymeleaf.cache=false